name: CI

on:
  push:
  pull_request:

jobs:
  Go:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.5

      - name: Format and Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: cli

      - name: Build
        run: go build
